name: CI/CD main_yml

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake g++

    - name: List files for debug
      run: ls -la


    - name: Configure
      run: cmake .

    - name: Build
      run: cmake --build .

    - name: Test code
      run: ctest --output-on-failure
