name: CI/CD main_yml

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      -main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake g++ doxygen

    - name: List files for debug
      run: ls -la


    - name: Configure
      run: cmake .

    - name: Build
      run: cmake --build .

    - name: Test code
      run: ctest --output-on-failure
    
    - name: Generate Documentation
      run: doxygen doxygen_file

    - name: Setup git identity
      if: github.event_name == 'push'
      run: |
        git config --global user.email "artemkasashin@yandex.ru"
        git config --global user.name "artemka332"
        
    - name: Commit documentation changes
      if: github.event_name == 'push'
      run: |
        git add docs/
        git commit -m "Auto-update documentation" || echo "No changes to commit"
        git push 
